/* =========================================================
   TutoresOn-Line · datos.js
   Datos de prueba (mock) que simulan la respuesta del API
   ========================================================= */

const TUTORES = [
  {
    id: 1,
    nombre: 'Laura Gómez',
    iniciales: 'LG',
    titulo: 'Ingeniera de Sistemas · 6 años de experiencia',
    materias: ['Matemáticas', 'Física'],
    niveles: ['Bachillerato', 'Universitario'],
    zona: 'Chapinero, Bogotá',
    modos: ['Virtual', 'Presencial'],
    precio: 28000,
    calificacion: 4.9,
    resenas: 128,
    verificado: true,
    bio: 'Docente universitaria especializada en cálculo, álgebra y física mecánica. Mi enfoque es resolver tus dudas con ejemplos prácticos y un plan de estudio claro para cada sesión.',
  },
  {
    id: 2,
    nombre: 'Andrés Ramírez',
    iniciales: 'AR',
    titulo: 'M. en Ciencias de la Computación',
    materias: ['Programación', 'Bases de Datos'],
    niveles: ['Universitario', 'Técnico'],
    zona: 'Virtual',
    modos: ['Virtual'],
    precio: 35000,
    calificacion: 4.8,
    resenas: 96,
    verificado: true,
    bio: 'Desarrollador backend con 8 años de experiencia. Te acompaño en Java, Python, SQL y estructuras de datos con proyectos reales.',
  },
  {
    id: 3,
    nombre: 'María Fernanda Ruiz',
    iniciales: 'MR',
    titulo: 'Licenciada en Idiomas',
    materias: ['Inglés'],
    niveles: ['Básico Primaria', 'Bachillerato'],
    zona: 'Usaquén, Bogotá',
    modos: ['Virtual', 'Presencial'],
    precio: 22000,
    calificacion: 5.0,
    resenas: 74,
    verificado: true,
    bio: 'Certificada Cambridge. Preparación para exámenes TOEFL/IELTS y conversación práctica con material personalizado.',
  },
  {
    id: 4,
    nombre: 'Carlos Mejía',
    iniciales: 'CM',
    titulo: 'Químico industrial',
    materias: ['Química', 'Biología'],
    niveles: ['Bachillerato'],
    zona: 'Kennedy, Bogotá',
    modos: ['Presencial'],
    precio: 20000,
    calificacion: 4.6,
    resenas: 41,
    verificado: false,
    bio: 'Experimentado preparador de laboratorio y simulacros Saber 11. Clases presenciales en zona sur de Bogotá.',
  },
  {
    id: 5,
    nombre: 'Sofía Vargas',
    iniciales: 'SV',
    titulo: 'Economista · MBA',
    materias: ['Economía', 'Estadística'],
    niveles: ['Universitario'],
    zona: 'Virtual',
    modos: ['Virtual'],
    precio: 32000,
    calificacion: 4.7,
    resenas: 58,
    verificado: true,
    bio: 'Experta en micro/macroeconomía, estadística inferencial y econometría. Ayudo con trabajos y parciales.',
  },
  {
    id: 6,
    nombre: 'Diego Hernández',
    iniciales: 'DH',
    titulo: 'Matemático · Profesor de colegio',
    materias: ['Matemáticas'],
    niveles: ['Básico Secundaria', 'Bachillerato'],
    zona: 'Suba, Bogotá',
    modos: ['Virtual', 'Presencial'],
    precio: 18000,
    calificacion: 4.8,
    resenas: 110,
    verificado: true,
    bio: 'Enfoque en fortalecimiento de bases: álgebra, geometría y trigonometría con ejercicios guiados paso a paso.',
  },
  {
    id: 7,
    nombre: 'Valentina Ortiz',
    iniciales: 'VO',
    titulo: 'Psicóloga · Coach académica',
    materias: ['Orientación Vocacional', 'Técnicas de Estudio'],
    niveles: ['Bachillerato', 'Universitario'],
    zona: 'Virtual',
    modos: ['Virtual'],
    precio: 26000,
    calificacion: 4.9,
    resenas: 63,
    verificado: true,
    bio: 'Acompaño en planificación del tiempo, manejo de ansiedad ante exámenes y elección de carrera universitaria.',
  },
  {
    id: 8,
    nombre: 'Julián Castro',
    iniciales: 'JC',
    titulo: 'Ingeniero Electrónico',
    materias: ['Física', 'Programación'],
    niveles: ['Universitario', 'Técnico'],
    zona: 'Teusaquillo, Bogotá',
    modos: ['Virtual', 'Presencial'],
    precio: 30000,
    calificacion: 4.5,
    resenas: 37,
    verificado: false,
    bio: 'Circuitos, electrónica analogica y programación de microcontroladores. Tutorías con laboratorio virtual.',
  },
];

const MATERIAS = [
  'Matemáticas',
  'Física',
  'Química',
  'Biología',
  'Inglés',
  'Programación',
  'Bases de Datos',
  'Economía',
  'Estadística',
  'Orientación Vocacional',
  'Técnicas de Estudio',
];

const NIVELES = [
  'Básico Primaria',
  'Básico Secundaria',
  'Bachillerato',
  'Universitario',
  'Técnico',
];

const ZONAS = [
  'Chapinero, Bogotá',
  'Usaquén, Bogotá',
  'Kennedy, Bogotá',
  'Suba, Bogotá',
  'Teusaquillo, Bogotá',
  'Virtual',
];

const SESIONES_ESTUDIANTE = [
  {
    id: 101,
    tutor: 'Laura Gómez',
    iniciales: 'LG',
    materia: 'Matemáticas · Cálculo integral',
    fecha: 'Jueves 15 de octubre, 4:00 p. m.',
    modo: 'Virtual',
    estado: 'Confirmada',
    duracion: '60 min',
    proxima: true,
  },
  {
    id: 102,
    tutor: 'Andrés Ramírez',
    iniciales: 'AR',
    materia: 'Programación · Estructuras de datos',
    fecha: 'Sábado 17 de octubre, 10:00 a. m.',
    modo: 'Virtual',
    estado: 'Pendiente de aprobación',
    duracion: '90 min',
    proxima: true,
  },
  {
    id: 103,
    tutor: 'María Fernanda Ruiz',
    iniciales: 'MR',
    materia: 'Inglés · Conversación B2',
    fecha: 'Lunes 5 de octubre, 6:00 p. m.',
    modo: 'Virtual',
    estado: 'Completada',
    duracion: '60 min',
    proxima: false,
    calificada: true,
  },
  {
    id: 104,
    tutor: 'Diego Hernández',
    iniciales: 'DH',
    materia: 'Matemáticas · Trigonometría',
    fecha: 'Miércoles 30 de septiembre, 3:00 p. m.',
    modo: 'Presencial',
    estado: 'Completada',
    duracion: '60 min',
    proxima: false,
    calificada: false,
  },
];

const SOLICITUDES_TUTOR = [
  {
    id: 201,
    estudiante: 'Andrés Palacios',
    iniciales: 'AP',
    materia: 'Física · Cinemática',
    fecha: 'Viernes 16 de octubre, 7:00 p. m.',
    modo: 'Virtual',
    estado: 'Pendiente',
  },
  {
    id: 202,
    estudiante: 'Camila Rojas',
    iniciales: 'CR',
    materia: 'Matemáticas · Derivadas',
    fecha: 'Sábado 17 de octubre, 9:00 a. m.',
    modo: 'Presencial',
    estado: 'Pendiente',
  },
  {
    id: 203,
    estudiante: 'Jorge Nieto',
    iniciales: 'JN',
    materia: 'Matemáticas · Integrales',
    fecha: 'Martes 13 de octubre, 5:00 p. m.',
    modo: 'Virtual',
    estado: 'Aceptada',
  },
  {
    id: 204,
    estudiante: 'Daniela Soto',
    iniciales: 'DS',
    materia: 'Física · Dinámica',
    fecha: 'Lunes 12 de octubre, 8:00 p. m.',
    modo: 'Virtual',
    estado: 'Rechazada',
  },
];

const RESENAS_TUTOR = [
  {
    autor: 'Andrés Palacios',
    iniciales: 'AP',
    estrellas: 5,
    fecha: '2 oct 2026',
    texto: 'Excelente tutora, explica muy claro y siempre llega con ejemplos resueltos. Saqué 4.5 en el parcial de cálculo gracias a estas sesiones.',
  },
  {
    autor: 'Camila Rojas',
    iniciales: 'CR',
    estrellas: 5,
    fecha: '28 sep 2026',
    texto: 'Muy puntual y organizada. Me armó un plan de estudio para el semestre que me sirvió mucho.',
  },
  {
    autor: 'Jorge Nieto',
    iniciales: 'JN',
    estrellas: 4,
    fecha: '21 sep 2026',
    texto: 'Buena explicación, solo quiso un poco más de tiempo extra pero sin costo adicional. Recomendada.',
  },
];

const AVABILITIES = {
  'Lunes': ['8:00', '9:00', '10:00', '16:00', '17:00'],
  'Martes': ['8:00', '9:00', '18:00', '19:00'],
  'Miércoles': ['10:00', '11:00', '16:00', '17:00', '18:00'],
  'Jueves': ['8:00', '9:00', '16:00', '17:00'],
  'Viernes': ['14:00', '15:00', '16:00'],
  'Sábado': ['9:00', '10:00', '11:00'],
  'Domingo': [],
};
